# Generated by Django 3.0.6 on 2021-01-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='bio',
            field=models.TextField(),
        ),
    ]
