# Generated by Django 3.0.6 on 2021-01-27 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_auto_20210126_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 14, 52, 37, 734037, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 14, 52, 37, 733293, tzinfo=utc)),
        ),
    ]
