# Generated by Django 3.0.6 on 2021-01-28 06:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_auto_20210127_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 6, 4, 57, 739832, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 6, 4, 57, 738631, tzinfo=utc)),
        ),
    ]
